# Generated by Django 3.2.16 on 2022-11-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='movie_genre',
        ),
    ]
