# Generated by Django 3.2.16 on 2022-11-22 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20221121_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='in_watchlists',
            field=models.ManyToManyField(blank=True, related_name='in_watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
