# Generated by Django 3.2.16 on 2022-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_movie_in_watchlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_approved',
            field=models.BooleanField(default=False),
        ),
    ]
