# Generated by Django 3.2.16 on 2022-11-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_review_movie_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_approved',
            field=models.BooleanField(default=False),
        ),
    ]
